### PR TITLE
add important newline to readme

### PR DESCRIPTION
**Pull request by Waterdrips**
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

### CODE REVIEW

**Comment by alexellis** [comment]
```yaml
mergers:
 - burtonr
 - LucasRoesler
 - alexellis
 - ewilde
 - johnmccabe
 - jonatasbaldin
 - kenfdev
 - martindekov
 - matipan
 - rgee0
 - stefanprodan
 - viveksyngh
 - Waterdrips
 - utsavanand2

must_approve:
- alexellis
- LucasRoesler
```

This means anyone from the first group can issue the merge command, if and only if there are exactly 2 reviews in approved state from the `must_approve` group. If the `must_approve` group is empty, anyone in the mergers group can merge without an approval.

**Comment by alexellis** [comment]
@LucasRoesler please approve

**Comment by LucasRoesler** [comment]
so confused, i never saw the original ping for this, i only saw the close notification :( sorry

**Pull request closed without merging**
