### PR TITLE
Sometimes you can't approve your own PR

### PR DESCRIPTION
**Pull request by alexellis**
Despite being a must approver

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
@LucasRoesler please approve this PR

**Review by burtonr — APPROVED** [review]
A helping hand... 👍

**Comment by burtonr** [comment]
Derek merge

**Comment by alexellis** [comment]
Now try `Derek merge`

**Comment by burtonr** [comment]
Derek merge

**Comment by alexellis** [comment]
```
derek-098.1.mk7m867c00z4@nuc    | needed 1 approvals, but had: 0
time="2020-01-16T22:14:41Z" level=info msg="Feedback: needed 1 approvals, but had: 0"
```

**Review by burtonr — APPROVED** [review]

**Comment by alexellis** [comment]
I think it's the filtering logic

**Comment by burtonr** [comment]
Derek merge

**Comment by burtonr** [comment]
Derek merge

**Comment by LucasRoesler** [comment]
Sorry I missed this earlier, but the result is super cool

**Pull request merged**
